//
//  Font data: eui_test_font
//  Auto-generated by ESGUI Font Generator v1.2.0 (二分查找优化版)
//
//  Params:
//    Size:   16 px
//    Threshold: 128
//    Sparse threshold: 26
//    Line height: 15 px
//    Base line:   12 px
//    Glyphs: 116
//    Cmaps:  3 (type0=2, type1=1)
//

#include "eui_test_font.h"

/* Bitmap blob (1736 bytes) */
static const eui_uint8_t eui_test_font_bitmap[] = {
    0x38, 0xC4, 0xB2, 0x79, 0x4D, 0x79, 0x5A, 0x66, 0x38, 0x00, 0x00, 0x01, 0x01, 0x01, 0x01, 0x01, 
    0x00, 0x00, 0x00, 0x80, 0xF0, 0xFE, 0xC6, 0xDE, 0xF0, 0x80, 0x00, 0x02, 0x03, 0x01, 0x00, 0x00, 
    0x00, 0x01, 0x03, 0x02, 0xFF, 0xFF, 0x93, 0x93, 0x93, 0x9F, 0xEE, 0x40, 0x01, 0x01, 0x01, 0x01, 
    0x01, 0x01, 0x00, 0x00, 0x70, 0xFC, 0x8E, 0x06, 0x02, 0x06, 0x8C, 0x88, 0x00, 0x00, 0x01, 0x03, 
    0x03, 0x03, 0x01, 0x00, 0xFF, 0xFF, 0x83, 0x83, 0x83, 0xC6, 0x7E, 0x38, 0x01, 0x01, 0x01, 0x01, 
    0x01, 0x00, 0x00, 0x00, 0xFE, 0xFE, 0x36, 0x26, 0x26, 0x36, 0x06, 0x00, 0x03, 0x03, 0x03, 0x03, 
    0x03, 0x03, 0x03, 0x00, 0xFE, 0xFE, 0x26, 0x26, 0x26, 0x36, 0x26, 0x00, 0x03, 0x03, 0x00, 0x00, 
    0x00, 0x00, 0x00, 0x00, 0x70, 0xF8, 0x8C, 0x06, 0x06, 0x26, 0xEC, 0xE0, 0x00, 0x00, 0x01, 0x03, 
    0x03, 0x03, 0x01, 0x03, 0x00, 0xFF, 0xFE, 0x10, 0x10, 0x10, 0xFF, 0xFF, 0x00, 0x01, 0x01, 0x00, 
    0x00, 0x00, 0x01, 0x01, 0x01, 0x03, 0xFF, 0xFF, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x40, 0xC0, 
    0x80, 0x81, 0x83, 0xFF, 0x03, 0x01, 0x00, 0x00, 0x01, 0x01, 0x01, 0x00, 0x00, 0x00, 0xFF, 0xFF, 
    0x18, 0x3C, 0x76, 0xC3, 0x81, 0x00, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x00, 0xFF, 
    0x80, 0x80, 0x80, 0x80, 0x00, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x00, 0xFF, 0x0E, 0x1C, 
    0x38, 0x0E, 0xFF, 0xFF, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0xFF, 0xFF, 0x0E, 0x38, 
    0x70, 0xFF, 0xFF, 0x01, 0x01, 0x00, 0x00, 0x00, 0x01, 0x01, 0x7C, 0xFE, 0x83, 0x83, 0x83, 0x83, 
    0xFE, 0x7C, 0x00, 0x00, 0x01, 0x01, 0x01, 0x01, 0x00, 0x00, 0xFE, 0xFF, 0x33, 0x33, 0x33, 0x1E, 
    0x0C, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7C, 0xFE, 0x87, 0x83, 0xC3, 0xC7, 0xFE, 0x3C, 
    0x00, 0x00, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0xFE, 0xFF, 0x33, 0x33, 0xF3, 0xDE, 0x0C, 0x01, 
    0x01, 0x00, 0x00, 0x00, 0x01, 0x01, 0x84, 0xCE, 0x9B, 0x93, 0xB3, 0xF7, 0x62, 0x00, 0x01, 0x01, 
    0x01, 0x01, 0x00, 0x00, 0x03, 0x03, 0x03, 0xFF, 0x03, 0x03, 0x03, 0x00, 0x00, 0x00, 0x01, 0x00, 
    0x00, 0x00, 0x7E, 0xFF, 0x80, 0x80, 0x80, 0xFE, 0xFF, 0x00, 0x00, 0x00, 0x01, 0x01, 0x01, 0x01, 
    0x00, 0x00, 0x00, 0x0F, 0x7C, 0xF0, 0xC0, 0xF8, 0x3F, 0x03, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 
    0x00, 0x00, 0x00, 0x00, 0x00, 0x1F, 0xFC, 0xC0, 0xF0, 0xF0, 0xC0, 0xFC, 0x1F, 0x00, 0x00, 0x00, 
    0x01, 0x01, 0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x00, 0x83, 0xEE, 0x7C, 0x38, 0xEE, 0xC7, 0x01, 
    0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x00, 0x07, 0x0E, 0xF8, 0xF8, 0x0E, 0x07, 0x00, 
    0x00, 0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x00, 0x82, 0xC3, 0xE3, 0xBB, 0x9F, 0x8F, 0x83, 0x01, 
    0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0xFE, 0xFE, 0x06, 0x00, 0x07, 0x0F, 0x0C, 0x00, 0x02, 0x07, 
    0x1C, 0xE0, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0x0C, 0x00, 0x02, 0x06, 0xFE, 0x00, 
    0x08, 0x0C, 0x0F, 0x00, 0xFE, 0xF7, 0x01, 0xBF, 0xFE, 0x3F, 0x3A, 0x26, 0x3A, 0x3F, 0x00, 0x00, 
    0x00, 0x00, 0x00, 0x00, 0x00, 0x30, 0x76, 0x7A, 0x4A, 0x7E, 0x7E, 0x40, 0x01, 0xFF, 0xFF, 0x88, 
    0x88, 0xF8, 0xF0, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x00, 0x18, 0x3E, 0x66, 0x42, 0x62, 0x26, 
    0x00, 0xC0, 0xF0, 0x30, 0x10, 0x32, 0xFE, 0x00, 0x00, 0x01, 0x03, 0x02, 0x03, 0x03, 0x03, 0x1C, 
    0x3E, 0x7E, 0x4A, 0x6A, 0x6E, 0x00, 0x08, 0x0C, 0xFE, 0x0F, 0x0B, 0x00, 0x00, 0x00, 0x01, 0x00, 
    0x00, 0x00, 0x1C, 0xBE, 0xA2, 0x22, 0xBE, 0xFE, 0x02, 0x00, 0x01, 0x01, 0x01, 0x01, 0x00, 0x00, 
    0x01, 0xFF, 0xFF, 0x08, 0x08, 0xF8, 0xF0, 0x00, 0x01, 0x01, 0x00, 0x00, 0x01, 0x01, 0x08, 0xFA, 
    0xFA, 0x00, 0x01, 0x01, 0x01, 0x01, 0x00, 0x08, 0xFA, 0xFA, 0x00, 0x06, 0x07, 0x01, 0x01, 0xFF, 
    0xFF, 0x70, 0xD8, 0x88, 0x00, 0x01, 0x01, 0x01, 0x00, 0x00, 0x01, 0x01, 0x00, 0xFF, 0xFF, 0x00, 
    0x01, 0x01, 0x01, 0x01, 0x00, 0x7E, 0x7E, 0x02, 0x7E, 0x7E, 0x06, 0x02, 0x7E, 0x00, 0x00, 0x7E, 
    0x7E, 0x02, 0x02, 0x7E, 0x7C, 0x1C, 0x3E, 0x66, 0x62, 0x66, 0x3E, 0x18, 0x00, 0xFE, 0xFE, 0x62, 
    0x62, 0x7E, 0x3C, 0x00, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x18, 0x3E, 0x66, 0x62, 0x66, 0xFE, 
    0xFE, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x00, 0x40, 0x7E, 0x7E, 0x06, 0x02, 0x02, 
    0x20, 0x6E, 0x5A, 0x5A, 0x7E, 0x30, 0x00, 0x0C, 0xFE, 0x8C, 0x8C, 0x00, 0x00, 0x00, 0x00, 0x01, 
    0x01, 0x00, 0x1E, 0x3E, 0x60, 0x60, 0x7E, 0x7E, 0x40, 0x00, 0x06, 0x3E, 0x70, 0x78, 0x1E, 0x06, 
    0x00, 0x00, 0x0E, 0x7C, 0x70, 0x1E, 0x1E, 0x70, 0x7C, 0x1E, 0x02, 0x40, 0x62, 0x7E, 0x1C, 0x3C, 
    0x66, 0x42, 0x00, 0x02, 0x9E, 0xBE, 0x20, 0xA0, 0xFE, 0x7E, 0x00, 0x00, 0x01, 0x01, 0x01, 0x01, 
    0x00, 0x00, 0x00, 0x42, 0x72, 0x7A, 0x5E, 0x46, 0x62, 0x40, 0xE0, 0xBE, 0x02, 0x00, 0x00, 0x00, 
    0x0F, 0x08, 0x00, 0xFE, 0xF7, 0x01, 0xBF, 0xFE, 0x3F, 0x3A, 0x26, 0x3A, 0x3F, 0x02, 0x02, 0xBE, 
    0x60, 0x00, 0x08, 0x08, 0x0F, 0x00, 0x00, 0xFE, 0xF7, 0x01, 0xBF, 0xFE, 0x3F, 0x3A, 0x26, 0x3A, 
    0x3F, 0x00, 0xC8, 0xE8, 0xFF, 0xCF, 0xE8, 0xFF, 0x4F, 0x08, 0x00, 0x00, 0x03, 0x00, 0x00, 0x03, 
    0x00, 0x00, 0x00, 0x00, 0x98, 0xBC, 0x36, 0xFF, 0x66, 0x6E, 0xCC, 0x00, 0x00, 0x01, 0x03, 0x03, 
    0x07, 0x03, 0x03, 0x01, 0x00, 0xFE, 0xF7, 0x01, 0xBF, 0xFE, 0x3F, 0x3A, 0x26, 0x3A, 0x3F, 0x00, 
    0xE0, 0xBE, 0x1B, 0x7B, 0xE6, 0xE0, 0x30, 0x00, 0x00, 0x00, 0x01, 0x01, 0x01, 0x00, 0x01, 0x01, 
    0x00, 0x00, 0xF8, 0x9E, 0x06, 0x00, 0x00, 0x03, 0x07, 0x0C, 0x00, 0x02, 0x06, 0xFC, 0xF8, 0x08, 
    0x0C, 0x07, 0x01, 0x00, 0x0E, 0x0F, 0x0E, 0x02, 0x18, 0x18, 0x7E, 0x7E, 0x18, 0x18, 0x07, 0x03, 
    0x00, 0x02, 0x00, 0x00, 0x00, 0x80, 0x70, 0x1C, 0x03, 0x00, 0x0C, 0x0F, 0x03, 0x00, 0x00, 0x00, 
    0x00, 0x00, 0xFC, 0xFE, 0x06, 0x02, 0xFE, 0xFC, 0x00, 0x00, 0x01, 0x03, 0x03, 0x03, 0x03, 0x01, 
    0x00, 0x00, 0x04, 0xFE, 0xFE, 0x00, 0x00, 0x00, 0x03, 0x03, 0x03, 0x03, 0x00, 0x00, 0x84, 0xC6, 
    0xE2, 0x72, 0x3E, 0x1C, 0x00, 0x00, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x00, 0x00, 0x86, 0x06, 
    0x32, 0x36, 0xFE, 0xDC, 0x00, 0x00, 0x01, 0x03, 0x03, 0x03, 0x03, 0x01, 0x00, 0x00, 0xE0, 0xF0, 
    0xDC, 0xCE, 0xFE, 0xC0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0x03, 0x03, 0x00, 0x00, 0xBE, 0x3E, 
    0x32, 0x32, 0xE2, 0xE2, 0x00, 0x01, 0x03, 0x03, 0x03, 0x03, 0x01, 0x00, 0xFC, 0xFE, 0x32, 0x32, 
    0xF6, 0xE4, 0x00, 0x00, 0x01, 0x03, 0x03, 0x03, 0x03, 0x01, 0x00, 0x00, 0x06, 0x06, 0xC2, 0xF2, 
    0x3E, 0x0E, 0x00, 0x00, 0x00, 0x03, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0xDC, 0xFE, 0x32, 0x32, 
    0xFE, 0xDC, 0x00, 0x00, 0x01, 0x03, 0x03, 0x03, 0x03, 0x01, 0x00, 0x00, 0x9C, 0xBE, 0x22, 0x22, 
    0xFE, 0xFC, 0x00, 0x00, 0x01, 0x03, 0x03, 0x03, 0x03, 0x01, 0x00, 0x12, 0x12, 0x12, 0x12, 0x12, 
    0x12, 0xFE, 0xF7, 0x01, 0xBF, 0xFE, 0x3F, 0x3A, 0x26, 0x3A, 0x3F, 0x02, 0x02, 0x02, 0x02, 0x02, 
    0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x00, 0x02, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 
    0x02, 0x00, 0x00, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x00, 0x80, 
    0x82, 0x86, 0x86, 0x86, 0x86, 0x86, 0x86, 0x86, 0x86, 0x80, 0x80, 0x00, 0x01, 0x01, 0x01, 0x01, 
    0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x20, 0xF8, 0xFE, 0x00, 0xF4, 0xF4, 0xDE, 0xDE, 
    0xD4, 0xF4, 0xE4, 0x00, 0x00, 0x0F, 0x0F, 0x08, 0x0F, 0x0F, 0x0A, 0x0A, 0x0A, 0x0F, 0x0F, 0x08, 
    0x00, 0x86, 0xE6, 0xFE, 0x96, 0xF6, 0x72, 0xF8, 0xFC, 0xFC, 0xFE, 0x00, 0x00, 0x00, 0x08, 0x0C, 
    0x07, 0x01, 0x00, 0x01, 0x09, 0x0D, 0x0F, 0x00, 0x00, 0x24, 0xE6, 0xE6, 0x26, 0x36, 0x0C, 0xFE, 
    0xFE, 0x0C, 0xFC, 0x00, 0x00, 0x06, 0x07, 0x04, 0x07, 0x0E, 0x0E, 0x07, 0x01, 0x0C, 0x07, 0x00, 
    0xFE, 0xFE, 0x82, 0x7E, 0x1E, 0xFE, 0xFE, 0x82, 0xFE, 0xFE, 0x03, 0x07, 0x04, 0x04, 0x04, 0x04, 
    0x04, 0x04, 0x07, 0x03, 0x00, 0xFE, 0x06, 0xD2, 0x5A, 0xFA, 0x7A, 0x5A, 0x82, 0xFE, 0xFE, 0x00, 
    0x0F, 0x0C, 0x08, 0x08, 0x0B, 0x0E, 0x0A, 0x08, 0x0F, 0x1F, 0x00, 0x30, 0x9C, 0xCF, 0x06, 0xF4, 
    0xF4, 0x04, 0xD4, 0x1C, 0x0C, 0x00, 0x06, 0x07, 0x00, 0x08, 0x1F, 0x0F, 0x00, 0x01, 0x07, 0x06, 
    0x00, 0xC4, 0xE4, 0xFC, 0x7E, 0x67, 0xF4, 0x64, 0x64, 0xE4, 0x04, 0x00, 0x00, 0x00, 0x07, 0x00, 
    0x00, 0x0F, 0x00, 0x06, 0x03, 0x00, 0x00, 0xF2, 0xDE, 0x9E, 0x00, 0xFF, 0xFE, 0xFC, 0xFE, 0xFF, 
    0x00, 0x00, 0x0C, 0x0C, 0x07, 0x02, 0x02, 0x02, 0x0F, 0x02, 0x02, 0x02, 0x00, 0x62, 0xFE, 0x66, 
    0xFE, 0xFE, 0x02, 0xD8, 0x6C, 0x77, 0x30, 0x00, 0x0C, 0x07, 0x00, 0x0F, 0x0F, 0x08, 0x0C, 0x06, 
    0x03, 0x01, 0x00, 0x00, 0xFC, 0xFC, 0xAE, 0xAE, 0xAE, 0xAC, 0xFC, 0xFC, 0x00, 0x00, 0x00, 0x06, 
    0x02, 0x06, 0x0E, 0x08, 0x0B, 0x08, 0x0C, 0x02, 0x06, 0x00, 0x00, 0x0C, 0x1C, 0x7C, 0xCC, 0x8E, 
    0xCC, 0x7C, 0x3C, 0x0C, 0x00, 0x00, 0x08, 0x0C, 0x06, 0x07, 0x03, 0x03, 0x06, 0x0C, 0x08, 0x00, 
    0x24, 0x7C, 0xF6, 0xFE, 0xE4, 0xFC, 0xFE, 0xFC, 0x6C, 0x20, 0x00, 0x0F, 0x0F, 0x0A, 0x0A, 0x0A, 
    0x0A, 0x0F, 0x00, 0x00, 0x00, 0x08, 0x88, 0xC8, 0x78, 0xFE, 0xFE, 0x78, 0xC8, 0x08, 0x08, 0x00, 
    0x00, 0x03, 0x01, 0x03, 0x02, 0x0F, 0x0F, 0x02, 0x03, 0x03, 0x03, 0x00, 0x00, 0x32, 0xA4, 0x84, 
    0xFE, 0xFA, 0xFE, 0xFE, 0xFC, 0xFC, 0xFE, 0x00, 0x00, 0x0E, 0x03, 0x08, 0x06, 0x03, 0x07, 0x04, 
    0x01, 0x0D, 0x0F, 0x00, 0x12, 0xB6, 0xA4, 0xF0, 0xF4, 0x50, 0x5E, 0x50, 0xF6, 0x00, 0x06, 0x0F, 
    0x01, 0x07, 0x0F, 0x01, 0x01, 0x0D, 0x0F, 0x00, 0x00, 0x36, 0xAC, 0x14, 0x5C, 0xEC, 0xF6, 0xC6, 
    0x6C, 0x5C, 0x14, 0x00, 0x08, 0x0F, 0x03, 0x02, 0x03, 0x0F, 0x0D, 0x05, 0x03, 0x0F, 0x0D, 0x00, 
    0x00, 0x32, 0xA6, 0x04, 0xEC, 0xE4, 0xFE, 0xFE, 0xBC, 0xE4, 0xCE, 0x00, 0x00, 0x0E, 0x0F, 0x00, 
    0x0B, 0x0F, 0x07, 0x03, 0x06, 0x0F, 0x09, 0x00, 0x00, 0x02, 0xFE, 0x90, 0x90, 0x90, 0x9E, 0x9E, 
    0x10, 0x18, 0x00, 0x08, 0x0F, 0x03, 0x00, 0x00, 0x00, 0x00, 0x0F, 0x0E, 0x00, 0x00, 0xF8, 0xFC, 
    0x2C, 0xEC, 0xFE, 0xAC, 0x2C, 0xF8, 0x00, 0x00, 0x01, 0x01, 0x01, 0x01, 0x0F, 0x0D, 0x09, 0x09, 
    0x0C, 0x06, 0x00, 0x30, 0xB6, 0xB6, 0x36, 0xF6, 0xF6, 0x36, 0xB6, 0x32, 0x30, 0x00, 0x06, 0x03, 
    0x01, 0x08, 0x0F, 0x07, 0x00, 0x01, 0x07, 0x04, 0x00, 0x1C, 0xFC, 0x3C, 0xAC, 0xF6, 0xA6, 0xAC, 
    0x6C, 0xFC, 0x0E, 0x00, 0x00, 0x0F, 0x0C, 0x0F, 0x0F, 0x0B, 0x0F, 0x0C, 0x0F, 0x00, 0x00, 0x64, 
    0x74, 0xF4, 0xF4, 0xFE, 0xFE, 0x3C, 0x3C, 0xBC, 0x24, 0x00, 0x00, 0x02, 0x0B, 0x0F, 0x0D, 0x04, 
    0x05, 0x03, 0x07, 0x0D, 0x08, 0x00, 0x00, 0x32, 0xF6, 0x00, 0x48, 0xC8, 0x48, 0xFE, 0xFE, 0x0A, 
    0x0C, 0x00, 0x00, 0x04, 0x0F, 0x06, 0x0C, 0x07, 0x06, 0x01, 0x0F, 0x0C, 0x0E, 0x00, 0x00, 0x11, 
    0xF7, 0x00, 0xF9, 0xF9, 0xFF, 0xFD, 0xEF, 0xFB, 0xF8, 0x00, 0x06, 0x03, 0x02, 0x05, 0x05, 0x04, 
    0x05, 0x04, 0x05, 0x04, 0x00, 0x40, 0x60, 0xFE, 0x40, 0x50, 0xD8, 0x4C, 0x46, 0x40, 0x60, 0x00, 
    0x00, 0x00, 0x0F, 0x0C, 0x04, 0x01, 0x02, 0x06, 0x0C, 0x08, 0xF8, 0xFA, 0x06, 0x80, 0xF2, 0xC2, 
    0x82, 0x02, 0xFE, 0xFE, 0x0F, 0x0F, 0x03, 0x01, 0x00, 0x00, 0x01, 0x0B, 0x0F, 0x07, 0x00, 0xF6, 
    0xF6, 0x16, 0xF6, 0x5E, 0xFE, 0xF6, 0x16, 0xF6, 0x02, 0x00, 0x0F, 0x0F, 0x0C, 0x0F, 0x0D, 0x0F, 
    0x0F, 0x0C, 0x0F, 0x00, 0x02, 0xF2, 0x1A, 0x1A, 0xDE, 0xDE, 0x1A, 0xFA, 0xF2, 0x02, 0x08, 0x0D, 
    0x04, 0x06, 0x03, 0x03, 0x06, 0x07, 0x0D, 0x08, 
};

/* Glyph descriptors (116 glyphs) */
static const FontGlyph eui_test_font_glyphs[] = {
    /* [  0] U+0040 '@' */
    {
        .bitmap_index = 0,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 9,
        .box_h       = 9,
    },
    /* [  1] U+0041 'A' */
    {
        .bitmap_index = 18,
        .adv_w       = 9,
        .ofs_x       = 0,
        .ofs_y       = -10,
        .box_w       = 9,
        .box_h       = 10,
    },
    /* [  2] U+0042 'B' */
    {
        .bitmap_index = 36,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 8,
        .box_h       = 9,
    },
    /* [  3] U+0043 'C' */
    {
        .bitmap_index = 52,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -10,
        .box_w       = 8,
        .box_h       = 10,
    },
    /* [  4] U+0044 'D' */
    {
        .bitmap_index = 68,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 8,
        .box_h       = 9,
    },
    /* [  5] U+0045 'E' */
    {
        .bitmap_index = 84,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -10,
        .box_w       = 8,
        .box_h       = 10,
    },
    /* [  6] U+0046 'F' */
    {
        .bitmap_index = 100,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -10,
        .box_w       = 8,
        .box_h       = 10,
    },
    /* [  7] U+0047 'G' */
    {
        .bitmap_index = 116,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -10,
        .box_w       = 8,
        .box_h       = 10,
    },
    /* [  8] U+0048 'H' */
    {
        .bitmap_index = 132,
        .adv_w       = 9,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 8,
        .box_h       = 9,
    },
    /* [  9] U+0049 'I' */
    {
        .bitmap_index = 148,
        .adv_w       = 6,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 5,
        .box_h       = 9,
    },
    /* [ 10] U+004A 'J' */
    {
        .bitmap_index = 158,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 8,
        .box_h       = 9,
    },
    /* [ 11] U+004B 'K' */
    {
        .bitmap_index = 174,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 8,
        .box_h       = 9,
    },
    /* [ 12] U+004C 'L' */
    {
        .bitmap_index = 190,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 7,
        .box_h       = 9,
    },
    /* [ 13] U+004D 'M' */
    {
        .bitmap_index = 204,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 8,
        .box_h       = 9,
    },
    /* [ 14] U+004E 'N' */
    {
        .bitmap_index = 220,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 7,
        .box_h       = 9,
    },
    /* [ 15] U+004F 'O' */
    {
        .bitmap_index = 234,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 8,
        .box_h       = 9,
    },
    /* [ 16] U+0050 'P' */
    {
        .bitmap_index = 250,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 7,
        .box_h       = 9,
    },
    /* [ 17] U+0051 'Q' */
    {
        .bitmap_index = 264,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 8,
        .box_h       = 10,
    },
    /* [ 18] U+0052 'R' */
    {
        .bitmap_index = 280,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 7,
        .box_h       = 9,
    },
    /* [ 19] U+0053 'S' */
    {
        .bitmap_index = 294,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 7,
        .box_h       = 9,
    },
    /* [ 20] U+0054 'T' */
    {
        .bitmap_index = 308,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 7,
        .box_h       = 9,
    },
    /* [ 21] U+0055 'U' */
    {
        .bitmap_index = 322,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 8,
        .box_h       = 9,
    },
    /* [ 22] U+0056 'V' */
    {
        .bitmap_index = 338,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 9,
        .box_h       = 9,
    },
    /* [ 23] U+0057 'W' */
    {
        .bitmap_index = 356,
        .adv_w       = 10,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 10,
        .box_h       = 9,
    },
    /* [ 24] U+0058 'X' */
    {
        .bitmap_index = 376,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 8,
        .box_h       = 9,
    },
    /* [ 25] U+0059 'Y' */
    {
        .bitmap_index = 392,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 8,
        .box_h       = 9,
    },
    /* [ 26] U+005A 'Z' */
    {
        .bitmap_index = 408,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 7,
        .box_h       = 9,
    },
    /* [ 27] U+005B '[' */
    {
        .bitmap_index = 422,
        .adv_w       = 4,
        .ofs_x       = 0,
        .ofs_y       = -11,
        .box_w       = 4,
        .box_h       = 13,
    },
    /* [ 28] U+005C '\' */
    {
        .bitmap_index = 430,
        .adv_w       = 5,
        .ofs_x       = 0,
        .ofs_y       = -10,
        .box_w       = 7,
        .box_h       = 13,
    },
    /* [ 29] U+005D ']' */
    {
        .bitmap_index = 444,
        .adv_w       = 4,
        .ofs_x       = 0,
        .ofs_y       = -11,
        .box_w       = 4,
        .box_h       = 13,
    },
    /* [ 30] U+005E '^' */
    {
        .bitmap_index = 452,
        .adv_w       = 7,
        .ofs_x       = 1,
        .ofs_y       = -12,
        .box_w       = 5,
        .box_h       = 15,
    },
    /* [ 31] U+005F '_' */
    {
        .bitmap_index = 462,
        .adv_w       = 5,
        .ofs_x       = -1,
        .ofs_y       = 0,
        .box_w       = 7,
        .box_h       = 2,
    },
    /* [ 32] U+0061 'a' */
    {
        .bitmap_index = 469,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 7,
        .box_h       = 7,
    },
    /* [ 33] U+0062 'b' */
    {
        .bitmap_index = 476,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 7,
        .box_h       = 9,
    },
    /* [ 34] U+0063 'c' */
    {
        .bitmap_index = 490,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 7,
        .box_h       = 7,
    },
    /* [ 35] U+0064 'd' */
    {
        .bitmap_index = 497,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -10,
        .box_w       = 7,
        .box_h       = 10,
    },
    /* [ 36] U+0065 'e' */
    {
        .bitmap_index = 511,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 7,
        .box_h       = 7,
    },
    /* [ 37] U+0066 'f' */
    {
        .bitmap_index = 518,
        .adv_w       = 6,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 38] U+0067 'g' */
    {
        .bitmap_index = 530,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 7,
        .box_h       = 9,
    },
    /* [ 39] U+0068 'h' */
    {
        .bitmap_index = 544,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 7,
        .box_h       = 9,
    },
    /* [ 40] U+0069 'i' */
    {
        .bitmap_index = 558,
        .adv_w       = 4,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 4,
        .box_h       = 9,
    },
    /* [ 41] U+006A 'j' */
    {
        .bitmap_index = 566,
        .adv_w       = 4,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 4,
        .box_h       = 11,
    },
    /* [ 42] U+006B 'k' */
    {
        .bitmap_index = 574,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 7,
        .box_h       = 9,
    },
    /* [ 43] U+006C 'l' */
    {
        .bitmap_index = 588,
        .adv_w       = 4,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 4,
        .box_h       = 9,
    },
    /* [ 44] U+006D 'm' */
    {
        .bitmap_index = 596,
        .adv_w       = 10,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 10,
        .box_h       = 7,
    },
    /* [ 45] U+006E 'n' */
    {
        .bitmap_index = 606,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 7,
        .box_h       = 7,
    },
    /* [ 46] U+006F 'o' */
    {
        .bitmap_index = 613,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 7,
        .box_h       = 7,
    },
    /* [ 47] U+0070 'p' */
    {
        .bitmap_index = 620,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 7,
        .box_h       = 10,
    },
    /* [ 48] U+0071 'q' */
    {
        .bitmap_index = 634,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 8,
        .box_h       = 10,
    },
    /* [ 49] U+0072 'r' */
    {
        .bitmap_index = 650,
        .adv_w       = 6,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 7,
    },
    /* [ 50] U+0073 's' */
    {
        .bitmap_index = 656,
        .adv_w       = 6,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 7,
    },
    /* [ 51] U+0074 't' */
    {
        .bitmap_index = 662,
        .adv_w       = 6,
        .ofs_x       = 0,
        .ofs_y       = -8,
        .box_w       = 6,
        .box_h       = 9,
    },
    /* [ 52] U+0075 'u' */
    {
        .bitmap_index = 674,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 7,
        .box_h       = 7,
    },
    /* [ 53] U+0076 'v' */
    {
        .bitmap_index = 681,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 8,
        .box_h       = 7,
    },
    /* [ 54] U+0077 'w' */
    {
        .bitmap_index = 689,
        .adv_w       = 10,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 10,
        .box_h       = 7,
    },
    /* [ 55] U+0078 'x' */
    {
        .bitmap_index = 699,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 8,
        .box_h       = 7,
    },
    /* [ 56] U+0079 'y' */
    {
        .bitmap_index = 707,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 8,
        .box_h       = 9,
    },
    /* [ 57] U+007A 'z' */
    {
        .bitmap_index = 723,
        .adv_w       = 6,
        .ofs_x       = 0,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 7,
    },
    /* [ 58] U+007B '{' */
    {
        .bitmap_index = 729,
        .adv_w       = 5,
        .ofs_x       = 0,
        .ofs_y       = -11,
        .box_w       = 5,
        .box_h       = 13,
    },
    /* [ 59] U+007C '|' */
    {
        .bitmap_index = 739,
        .adv_w       = 7,
        .ofs_x       = 1,
        .ofs_y       = -12,
        .box_w       = 5,
        .box_h       = 15,
    },
    /* [ 60] U+007D '}' */
    {
        .bitmap_index = 749,
        .adv_w       = 5,
        .ofs_x       = 0,
        .ofs_y       = -11,
        .box_w       = 5,
        .box_h       = 13,
    },
    /* [ 61] U+0021 '!' */
    {
        .bitmap_index = 759,
        .adv_w       = 7,
        .ofs_x       = 1,
        .ofs_y       = -12,
        .box_w       = 5,
        .box_h       = 15,
    },
    /* [ 62] U+0023 '#' */
    {
        .bitmap_index = 769,
        .adv_w       = 10,
        .ofs_x       = 0,
        .ofs_y       = -10,
        .box_w       = 9,
        .box_h       = 10,
    },
    /* [ 63] U+0024 '$' */
    {
        .bitmap_index = 787,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -10,
        .box_w       = 9,
        .box_h       = 12,
    },
    /* [ 64] U+0025 '%' */
    {
        .bitmap_index = 805,
        .adv_w       = 7,
        .ofs_x       = 1,
        .ofs_y       = -12,
        .box_w       = 5,
        .box_h       = 15,
    },
    /* [ 65] U+0026 '&' */
    {
        .bitmap_index = 815,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -9,
        .box_w       = 9,
        .box_h       = 10,
    },
    /* [ 66] U+0028 '(' */
    {
        .bitmap_index = 833,
        .adv_w       = 5,
        .ofs_x       = 0,
        .ofs_y       = -11,
        .box_w       = 5,
        .box_h       = 13,
    },
    /* [ 67] U+0029 ')' */
    {
        .bitmap_index = 843,
        .adv_w       = 5,
        .ofs_x       = 0,
        .ofs_y       = -11,
        .box_w       = 4,
        .box_h       = 13,
    },
    /* [ 68] U+002A '*' */
    {
        .bitmap_index = 851,
        .adv_w       = 5,
        .ofs_x       = 0,
        .ofs_y       = -10,
        .box_w       = 5,
        .box_h       = 5,
    },
    /* [ 69] U+002B '+' */
    {
        .bitmap_index = 856,
        .adv_w       = 8,
        .ofs_x       = 1,
        .ofs_y       = -8,
        .box_w       = 6,
        .box_h       = 7,
    },
    /* [ 70] U+002C ',' */
    {
        .bitmap_index = 862,
        .adv_w       = 5,
        .ofs_x       = 1,
        .ofs_y       = -1,
        .box_w       = 2,
        .box_h       = 3,
    },
    /* [ 71] U+002E '.' */
    {
        .bitmap_index = 864,
        .adv_w       = 3,
        .ofs_x       = 0,
        .ofs_y       = -2,
        .box_w       = 3,
        .box_h       = 2,
    },
    /* [ 72] U+002F '/' */
    {
        .bitmap_index = 867,
        .adv_w       = 7,
        .ofs_x       = 0,
        .ofs_y       = -10,
        .box_w       = 7,
        .box_h       = 13,
    },
    /* [ 73] U+0030 '0' */
    {
        .bitmap_index = 881,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -10,
        .box_w       = 8,
        .box_h       = 10,
    },
    /* [ 74] U+0031 '1' */
    {
        .bitmap_index = 897,
        .adv_w       = 6,
        .ofs_x       = 0,
        .ofs_y       = -10,
        .box_w       = 6,
        .box_h       = 10,
    },
    /* [ 75] U+0032 '2' */
    {
        .bitmap_index = 909,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -10,
        .box_w       = 8,
        .box_h       = 10,
    },
    /* [ 76] U+0033 '3' */
    {
        .bitmap_index = 925,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -10,
        .box_w       = 8,
        .box_h       = 10,
    },
    /* [ 77] U+0034 '4' */
    {
        .bitmap_index = 941,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -10,
        .box_w       = 8,
        .box_h       = 10,
    },
    /* [ 78] U+0035 '5' */
    {
        .bitmap_index = 957,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -10,
        .box_w       = 7,
        .box_h       = 10,
    },
    /* [ 79] U+0036 '6' */
    {
        .bitmap_index = 971,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -10,
        .box_w       = 8,
        .box_h       = 10,
    },
    /* [ 80] U+0037 '7' */
    {
        .bitmap_index = 987,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -10,
        .box_w       = 8,
        .box_h       = 10,
    },
    /* [ 81] U+0038 '8' */
    {
        .bitmap_index = 1003,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -10,
        .box_w       = 8,
        .box_h       = 10,
    },
    /* [ 82] U+0039 '9' */
    {
        .bitmap_index = 1019,
        .adv_w       = 8,
        .ofs_x       = 0,
        .ofs_y       = -10,
        .box_w       = 8,
        .box_h       = 10,
    },
    /* [ 83] U+003D '=' */
    {
        .bitmap_index = 1035,
        .adv_w       = 8,
        .ofs_x       = 1,
        .ofs_y       = -7,
        .box_w       = 6,
        .box_h       = 6,
    },
    /* [ 84] U+2193 ' ' */
    {
        .bitmap_index = 1041,
        .adv_w       = 7,
        .ofs_x       = 1,
        .ofs_y       = -12,
        .box_w       = 5,
        .box_h       = 15,
    },
    /* [ 85] U+4E00 ' ' */
    {
        .bitmap_index = 1051,
        .adv_w       = 13,
        .ofs_x       = 1,
        .ofs_y       = -6,
        .box_w       = 11,
        .box_h       = 3,
    },
    /* [ 86] U+4E09 ' ' */
    {
        .bitmap_index = 1062,
        .adv_w       = 14,
        .ofs_x       = 1,
        .ofs_y       = -10,
        .box_w       = 12,
        .box_h       = 11,
    },
    /* [ 87] U+4E8C ' ' */
    {
        .bitmap_index = 1086,
        .adv_w       = 14,
        .ofs_x       = 0,
        .ofs_y       = -10,
        .box_w       = 13,
        .box_h       = 10,
    },
    /* [ 88] U+503C ' ' */
    {
        .bitmap_index = 1112,
        .adv_w       = 14,
        .ofs_x       = 1,
        .ofs_y       = -11,
        .box_w       = 12,
        .box_h       = 12,
    },
    /* [ 89] U+5217 ' ' */
    {
        .bitmap_index = 1136,
        .adv_w       = 14,
        .ofs_x       = 1,
        .ofs_y       = -11,
        .box_w       = 12,
        .box_h       = 13,
    },
    /* [ 90] U+52A8 ' ' */
    {
        .bitmap_index = 1160,
        .adv_w       = 14,
        .ofs_x       = 1,
        .ofs_y       = -11,
        .box_w       = 12,
        .box_h       = 13,
    },
    /* [ 91] U+56DB ' ' */
    {
        .bitmap_index = 1184,
        .adv_w       = 14,
        .ofs_x       = 2,
        .ofs_y       = -10,
        .box_w       = 10,
        .box_h       = 11,
    },
    /* [ 92] U+56FE ' ' */
    {
        .bitmap_index = 1204,
        .adv_w       = 14,
        .ofs_x       = 1,
        .ofs_y       = -11,
        .box_w       = 11,
        .box_h       = 13,
    },
    /* [ 93] U+5C14 ' ' */
    {
        .bitmap_index = 1226,
        .adv_w       = 14,
        .ofs_x       = 1,
        .ofs_y       = -11,
        .box_w       = 11,
        .box_h       = 13,
    },
    /* [ 94] U+5E03 ' ' */
    {
        .bitmap_index = 1248,
        .adv_w       = 14,
        .ofs_x       = 1,
        .ofs_y       = -11,
        .box_w       = 11,
        .box_h       = 13,
    },
    /* [ 95] U+5F39 ' ' */
    {
        .bitmap_index = 1270,
        .adv_w       = 14,
        .ofs_x       = 1,
        .ofs_y       = -11,
        .box_w       = 11,
        .box_h       = 13,
    },
    /* [ 96] U+5F62 ' ' */
    {
        .bitmap_index = 1292,
        .adv_w       = 14,
        .ofs_x       = 1,
        .ofs_y       = -11,
        .box_w       = 11,
        .box_h       = 13,
    },
    /* [ 97] U+606F ' ' */
    {
        .bitmap_index = 1314,
        .adv_w       = 14,
        .ofs_x       = 1,
        .ofs_y       = -11,
        .box_w       = 12,
        .box_h       = 13,
    },
    /* [ 98] U+6587 ' ' */
    {
        .bitmap_index = 1338,
        .adv_w       = 11,
        .ofs_x       = 0,
        .ofs_y       = -11,
        .box_w       = 11,
        .box_h       = 13,
    },
    /* [ 99] U+666E ' ' */
    {
        .bitmap_index = 1360,
        .adv_w       = 14,
        .ofs_x       = 2,
        .ofs_y       = -11,
        .box_w       = 10,
        .box_h       = 13,
    },
    /* [100] U+672C ' ' */
    {
        .bitmap_index = 1380,
        .adv_w       = 14,
        .ofs_x       = 1,
        .ofs_y       = -11,
        .box_w       = 12,
        .box_h       = 13,
    },
    /* [101] U+6D4B ' ' */
    {
        .bitmap_index = 1404,
        .adv_w       = 14,
        .ofs_x       = 1,
        .ofs_y       = -11,
        .box_w       = 12,
        .box_h       = 12,
    },
    /* [102] U+6D88 ' ' */
    {
        .bitmap_index = 1428,
        .adv_w       = 14,
        .ofs_x       = 2,
        .ofs_y       = -11,
        .box_w       = 10,
        .box_h       = 12,
    },
    /* [103] U+6EDA ' ' */
    {
        .bitmap_index = 1448,
        .adv_w       = 14,
        .ofs_x       = 1,
        .ofs_y       = -11,
        .box_w       = 12,
        .box_h       = 13,
    },
    /* [104] U+6F14 ' ' */
    {
        .bitmap_index = 1472,
        .adv_w       = 14,
        .ofs_x       = 1,
        .ofs_y       = -11,
        .box_w       = 12,
        .box_h       = 13,
    },
    /* [105] U+7247 ' ' */
    {
        .bitmap_index = 1496,
        .adv_w       = 14,
        .ofs_x       = 2,
        .ofs_y       = -11,
        .box_w       = 11,
        .box_h       = 13,
    },
    /* [106] U+7535 ' ' */
    {
        .bitmap_index = 1518,
        .adv_w       = 14,
        .ofs_x       = 2,
        .ofs_y       = -11,
        .box_w       = 10,
        .box_h       = 13,
    },
    /* [107] U+793A ' ' */
    {
        .bitmap_index = 1538,
        .adv_w       = 14,
        .ofs_x       = 1,
        .ofs_y       = -11,
        .box_w       = 11,
        .box_h       = 13,
    },
    /* [108] U+7A97 ' ' */
    {
        .bitmap_index = 1560,
        .adv_w       = 14,
        .ofs_x       = 1,
        .ofs_y       = -11,
        .box_w       = 11,
        .box_h       = 13,
    },
    /* [109] U+8868 ' ' */
    {
        .bitmap_index = 1582,
        .adv_w       = 14,
        .ofs_x       = 1,
        .ofs_y       = -11,
        .box_w       = 12,
        .box_h       = 13,
    },
    /* [110] U+8BD5 ' ' */
    {
        .bitmap_index = 1606,
        .adv_w       = 14,
        .ofs_x       = 1,
        .ofs_y       = -11,
        .box_w       = 12,
        .box_h       = 13,
    },
    /* [111] U+901A ' ' */
    {
        .bitmap_index = 1630,
        .adv_w       = 14,
        .ofs_x       = 1,
        .ofs_y       = -10,
        .box_w       = 11,
        .box_h       = 12,
    },
    /* [112] U+957F ' ' */
    {
        .bitmap_index = 1652,
        .adv_w       = 14,
        .ofs_x       = 1,
        .ofs_y       = -11,
        .box_w       = 11,
        .box_h       = 13,
    },
    /* [113] U+95EA ' ' */
    {
        .bitmap_index = 1674,
        .adv_w       = 14,
        .ofs_x       = 2,
        .ofs_y       = -11,
        .box_w       = 10,
        .box_h       = 13,
    },
    /* [114] U+9762 ' ' */
    {
        .bitmap_index = 1694,
        .adv_w       = 14,
        .ofs_x       = 1,
        .ofs_y       = -11,
        .box_w       = 11,
        .box_h       = 12,
    },
    /* [115] U+9875 ' ' */
    {
        .bitmap_index = 1716,
        .adv_w       = 14,
        .ofs_x       = 2,
        .ofs_y       = -11,
        .box_w       = 10,
        .box_h       = 13,
    },
};

/* Unicode sparse list (55 codepoints) —— 已按 Unicode 升序排列，适配二分查找 */
static const eui_uint16_t eui_test_font_unicode_list_61[] = {
    0x0021, 0x0023, 0x0024, 0x0025, 0x0026, 0x0028, 0x0029, 0x002A, 
    0x002B, 0x002C, 0x002E, 0x002F, 0x0030, 0x0031, 0x0032, 0x0033, 
    0x0034, 0x0035, 0x0036, 0x0037, 0x0038, 0x0039, 0x003D, 0x2193, 
    0x4E00, 0x4E09, 0x4E8C, 0x503C, 0x5217, 0x52A8, 0x56DB, 0x56FE, 
    0x5C14, 0x5E03, 0x5F39, 0x5F62, 0x606F, 0x6587, 0x666E, 0x672C, 
    0x6D4B, 0x6D88, 0x6EDA, 0x6F14, 0x7247, 0x7535, 0x793A, 0x7A97, 
    0x8868, 0x8BD5, 0x901A, 0x957F, 0x95EA, 0x9762, 0x9875, 
};

/* Cmap tables (3 entries) */
static const FontCmap eui_test_font_cmaps[] = {
    {
        .range_start    = 0x0040,  /* U+0040 ~ U+005F */
        .range_length   = 32,
        .glyph_id_start = 0,
        .unicode_list   = ESGUI_NULL,
        .list_length    = 0,
        .type           = 0,
    },
    {
        .range_start    = 0x0061,  /* U+0061 ~ U+007D */
        .range_length   = 29,
        .glyph_id_start = 32,
        .unicode_list   = ESGUI_NULL,
        .list_length    = 0,
        .type           = 0,
    },
    {
        .range_start    = 0,
        .range_length   = 0,
        .glyph_id_start = 61,
        .unicode_list   = eui_test_font_unicode_list_61,
        .list_length    = 55,
        .type           = 1,
    },
};

const Font eui_test_font = {
    .bitmap      = eui_test_font_bitmap,
    .glyphs      = eui_test_font_glyphs,
    .cmaps       = eui_test_font_cmaps,
    .cmap_num    = 3,
    .line_height = 15,
    .base_line   = 12,
};
